// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycawqcgoqjkddagdnwuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYXdxY2dvcWprZGRhZ2Rud3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjE5NzMsImV4cCI6MjA2MTQzNzk3M30.eNzKn_HZd5oU-XKX9rEx63Ka3vSpAtqnJLf6n7MCt4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);